# Generated by Django 2.2.5 on 2019-09-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguroencasa', '0003_auto_20190906_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_from',
            field=models.EmailField(default='afoone@hotmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
